sudo: false
language: cpp

compiler:
  - gcc
  - clang

before_install:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then openssl aes-256-cbc -K $encrypted_53aee1835f86_key -iv $encrypted_53aee1835f86_iv -in .dropbox_uploader.enc -out .dropbox_uploader -d; fi

install:
  - export COMPILER_NAME=$CC
  - if [ "$CXX" = "g++" ]; then export CXX=g++-5 CC=gcc-5; fi
  - if [ "$CXX" = "clang++" ]; then export CXX=clang++-3.6 CC=clang-3.6; fi

before_script :
  - make deps

script:
  - make all

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./deploy.sh; fi

addons:
  apt:
    sources:
      - r-packages-precise
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - g++-5
      - clang-3.6
      - libncurses5-dev

