sudo: false

matrix:
  include:
    - env: COMPILER_NAME=gcc _CXX=g++-5 _CC=gcc-5
      addons:
        apt:
          packages:
            - ed
            - g++-5
            - libxml2
            - libxslt1.1
            - libncurses5-dev
          sources: &sources
            - r-packages-precise
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
    - env: COMPILER_NAME=clang _CXX=clang++-3.8 _CC=clang-3.8
      addons:
        apt:
          packages:
            - ed
            - libxml2
            - clang-3.8
            - libxslt1.1
            - libncurses5-dev
          sources: *sources

before_install:
  - if [ -n "$TRAVIS_PULL_REQUEST" ]; then openssl aes-256-cbc -K $encrypted_53aee1835f86_key -iv $encrypted_53aee1835f86_iv -in .dropbox_uploader.enc -out .dropbox_uploader -d; fi

install:
  - export PATH="$HOME/bin:$PATH"
  - export CXX="$_CXX" CC="$_CC"
  -
  - mkdir ~/bin
  - wget --no-check-certificate --no-clobber -O /tmp/tools/waf https://waf.io/waf-1.8.14 || true
  - wget --no-clobber -O /tmp/tools/cloc http://heanet.dl.sourceforge.net/project/cloc/cloc/v1.64/cloc-1.64.pl || true
  - wget --no-clobber -O /tmp/tools/xmlstarlet.deb http://ftp.slackware.com/pub/ubuntu/pool/universe/x/xmlstarlet/xmlstarlet_1.6.1-1_amd64.deb || true
  - wget --no-clobber -O /tmp/tools/dropbox_uploader https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh || true
  # Need to do this here, because storing cache happens before after_success
  - install -t ~/bin /tmp/tools/waf /tmp/tools/dropbox_uploader

before_script :
  - export LDFLAGS="-static-libstdc++ -static-libgcc"
  - waf configure

script:
  - waf
  - strip --strip-all --remove-section=.comment --remove-section=.note build/gaem

after_success:
  - if [ -n "$TRAVIS_PULL_REQUEST" ]; then dpkg -x /tmp/tools/xmlstarlet.deb /tmp/tools/xmlstarlet; fi
  - if [ -n "$TRAVIS_PULL_REQUEST" ]; then install -t ~/bin /tmp/tools/xmlstarlet/usr/bin/xmlstarlet /tmp/tools/cloc; fi
  - if [ -n "$TRAVIS_PULL_REQUEST" ]; then ./changelog.sh; fi
  - if [ -n "$TRAVIS_PULL_REQUEST" ]; then ./report.sh; fi
  - if [ -n "$TRAVIS_PULL_REQUEST" ]; then ./deploy.sh --newest --report; fi

cache:
  apt: true
  directories:
    - /tmp/tools
