sudo: false
language: cpp
git:
  depth: 1

compiler:
  - gcc
  - clang

before_install:
  - if [ -n "$TRAVIS_PULL_REQUEST" ]; then openssl aes-256-cbc -K $encrypted_53aee1835f86_key -iv $encrypted_53aee1835f86_iv -in .dropbox_uploader.enc -out .dropbox_uploader -d; fi

install:
  - export COMPILER_NAME=$CC
  - export PATH="$HOME/bin:$PATH"
  - if [ "$CXX" = "g++" ]; then export CXX=g++-5 CC=gcc-5; fi
  - if [ "$CXX" = "clang++" ]; then export CXX=clang++-3.6 CC=clang-3.6; fi

before_script :
  - make deps

script:
  - make all

after_success:
  - if [ -n "$TRAVIS_PULL_REQUEST" ]; then ./deploy.sh; fi
  - if [ -n "$TRAVIS_PULL_REQUEST" ]; then mkdir ~/bin && curl -o ~/bin/cloc http://heanet.dl.sourceforge.net/project/cloc/cloc/v1.64/cloc-1.64.pl && chmod +x ~/bin/cloc; fi
  - if [ -n "$TRAVIS_PULL_REQUEST" ]; then mkdir ~/tmp && curl -o ~/tmp/xmlstarlet.deb http://ftp.slackware.com/pub/ubuntu/pool/universe/x/xmlstarlet/xmlstarlet_1.6.1-1_amd64.deb && dpkg -x ~/tmp/xmlstarlet.deb ~/tmp/xmlstarlet/ && cp ~/tmp/xmlstarlet/usr/bin/xmlstarlet ~/bin/xmlstarlet; fi
  - if [ -n "$TRAVIS_PULL_REQUEST" ]; then ./report.sh; fi
  - if [ -n "$TRAVIS_PULL_REQUEST" ]; then ./deploy.sh --report; fi

addons:
  apt:
    sources:
      - r-packages-precise
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - g++-5
      - libxml2
      - libxslt1.1
      - clang-3.6
      - libncurses5-dev
