#!/bin/bash --verbose

glog1='git log -1'
xmledit='xmlstarlet edit --inplace --ps'
docname='Gaem line report -- generated by CLOC'
date_format='%d.%m.%y %r'
external_css='https://cdn.rawgit.com/kristopolous/BOOTSTRA.386/master/v2.3.1/bootstrap/css/bootstrap.css
              https://cdnjs.cloudflare.com/ajax/libs/octicons/3.1.0/octicons.min.css'
external_js='http://code.jquery.com/jquery.min.js https://cdn.rawgit.com/kristopolous/BOOTSTRA.386/master/v2.3.1/bootstrap/js/bootstrap.min.js'
github_octicon='<span class="octicon octicon-mark-github"></span>'

GHUsrProj() {
	echo "https://github.com/$1/$2/"
}
xmlstarlet --version
apt-cache showpkg xmlstarlet
insertAll() {
	for elem in $6
	do
		$xmledit --subnode "//*[local-name()=\"$3\"]"      -t elem -n "$1TMP"            \
		         --subnode "//*[local-name()=\"$1TMP\"]"   -t attr -n "$2"    -v "$elem" \
		         --rename  "//*[local-name()=\"$1TMP\"]"                      -v "$1"    \
		         cloc.xsl
	done
	$xmledit --insert "//*[local-name()=\"$1\"]" -t attr -n "$4" -v "$5" cloc.xsl
}

rm -f report.html report.xml cloc.xsl

cloc --3 --by-file-by-lang --by-percent cb --xml --xsl=1 --progress-rate=10 --out=report.xml --force-lang=Makefile source/ Makefile
$xmledit --append  '//*[@select="@blank" or @select="@comment"]'                                     -t text -n ''        -v '%'                                                                                                    \
         --subnode '//*[local-name()="body"]'                                                        -t text -n ''        -v 'APPEND_MARKER'                                                                                        \
         --subnode '//*[local-name()="head"]'                                                        -t elem -n 'metaTMP' -v ''                                                                                                     \
         --subnode '//*[(local-name()="td" or local-name()="th") and count(preceding-sibling::*)>0]' -t attr -n 'class'   -v 'text-center'                                                                                          \
         --subnode '//*[local-name()="table"]'                                                       -t attr -n 'class'   -v 'table table-bordered table-condensed table-hover'                                                     \
         --subnode '//*[local-name()="body"]'                                                        -t elem -n 'script'  -v 'window._386 = {fastLoad: true};'                                                                      \
         --subnode '//*[local-name()="metaTMP"]'                                                     -t attr -n 'name'    -v 'viewport'                                                                                             \
         --subnode '//*[local-name()="metaTMP"]'                                                     -t attr -n 'content' -v 'width=device-width, initial-scale=1.0'                                                                \
         --rename  '//*[local-name()="metaTMP"]'                                                                          -v 'meta'                                                                                                 \
         --update  '//*[local-name()="title"]'                                                                            -v "$docname"                                                                                             \
         --rename  '//*[@select="results/header"]/..'                                                                     -v 'h1'                                                                                                   \
         --update  '//*[@select="results/header"]/..'                                                                     -v "$docname"                                                                                             \
         --delete  '//*[local-name()="style"]'                                                                                                                                                                                      \
         cloc.xsl
insertAll 'link'   'href' 'head' 'rel'  'stylesheet'      "$external_css"
insertAll 'script' 'src'  'body' 'type' 'text/javascript' "$external_js"
$xmledit --subnode '//*[local-name()="head"]'  -t elem -n 'style' -v 'body{margin:1em}tr,th,td{padding:.1em .16em}abbr[title]{text-decoration:none}a{color:yellow}small:before{content: '\''*note: '\''}' \
         --subnode '//*[local-name()="style"]' -t attr -n 'type'  -v 'text/css'                                                                                                                           \
         cloc.xsl

{
	echo '<!DOCTYPE html PUBLIC'
	echo '  "-//W3C//DTD XHTML 1.0 Transitional//EN"'
	echo '  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">'

	xmlstarlet transform cloc.xsl report.xml | sed -r 's:(meta.+charset.+)>:\1 />:g'
} | gawk "{sub(/APPEND_MARKER/, \"$({                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                \
	$glog1 --pretty='<br /><p>Latest commit: <a href="'"$(GHUsrProj Skorezore Gaem)"'commit/%H/">%s</a> by <a href="mailto:%cE">%cN</a> on ';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \
	date -d "$($glog1 --date=rfc --pretty='%ad')" +"$date_format</p>";                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 \
	echo '<div id="footer"><address><a href="'"$(GHUsrProj Skorezore Gaem)"'">Gaem</a> created and maintained by <a href="mailto:skorezore@gmail.com?cc=nabijaczleweli@gmail.com&amp;subject=Gaem%20-%20">Skorezore &amp; nabijaczleweli</a>(<a href="'"$(GHUsrProj Skorezore)"'">'"$github_octicon"'</a> &amp; <a href="'"$(GHUsrProj nabijaczleweli)"'">'"$github_octicon"'</a>)<br /><a href="'"$(GHUsrProj Skorezore Gaem)"'blob/master/report.sh">Line report generator script</a> by <a href="mailto:nabijaczleweli@gmail.com?cc=skorezore@gmail.com&amp;subject=Gaem%20-%20line%20report%20-%20">nabijaczleweli</a></address>'; \
	date +"<small>generated by <a class=\" initialism\" href=\"http://cloc.sourceforge.net\">CLOC</a> at $date_format</small><br />";                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  \
	echo echo '<small>these metrics are <em>not</em> 100% accurate because smart counting <span class="initialism">SLOC</span> is tricky</small><br /><small>uses the *amazing* <a href="http://getbootstrap.com/">bootstrap</a> theme <a class=" initialism" href="'"$(GHUsrProj kristopolous BOOTSTRA.386)"'">BOOTSTRA.386</a> by <a href="'"$(GHUsrProj kristopolous)"'"><abbr title="Chris McKenzie">kristopolous</abbr></a></small></div>';                                                                                                                                                                                       \
} | sed -e 's/"/\\"/g' -e 's/&/\\\&/g' -e 's/&/\\\&/g' | awk 1 ORS='')\"); print}" > report.html
# Basically, we need to do this, because XMLStarlet escapes all XML we're generating here, and building it by hand is a *gigantic* PITA
